### ISSUE TITLE
rtMedia Core Plugin - Release Checklist

### ISSUE THREAD

**Issue by pooja-muchandikar** [rtCamp/rtMedia#1842]
We are about to release the core plugin, before releasing we need to follow the below checklist.

- [x] Test Develop branch thoroughly
- [x] Once develop is merged to master, Test Master branch, check if new version is getting reflected
- [x] Test with all add-ons of rtMedia
- [ ] Perform after release steps.

**Comment by thebengalboy** [comment]
@pavanpatil1 If after release steps are done, please close the issue.

**Comment by pavanpatil1** [comment]
Yes, After release steps are done hence closing this issue
