### ISSUE TITLE
rtMedia Core v4.6.11 Plugin - Release Checklist

### ISSUE THREAD

**Issue by pooja-muchandikar** [rtCamp/rtMedia#1896]
We are about to release the core plugin, before releasing we need to follow the below checklist.

- [ ] Test Develop branch thoroughly
- [ ] Once develop is merged to master, Test Master branch, check if new version is getting reflected
- [ ] Test with rtMedia Premium if everything is working fine, as all addons are included in Premium now
- [ ] Perform after release steps.

**Comment by pooja-muchandikar** [comment]
@Pradeep1308 

Updated Readme as per this document https://docs.google.com/document/d/19r-IPoqDeWFx1b0loBSAuJ24p9Hm4fEEvNbt2uluVd4/edit

**Comment by pavanpatil1** [comment]
Closing this issue as done.
