### ISSUE TITLE
rtMedia 3.0 - Release checklist for  1st version

### ISSUE THREAD

**Issue by rahul286** [rtCamp/rtMedia#329]
- [x] BuddyPress > User > Media ( @desaiuditd )
- [x] BuddyPress > Group > Media ( @desaiuditd )
- [x] Album - create, edit, delete, merge, move photo ( @joshuaabenazer )
- [x] Switching to WordPress Comments. DB migration script for old activities ( @faishal, @desaiuditd )
- [x] DB migration script for 2-way sync between activities & comments ( @faishal, @desaiuditd )
- [x] Image Editing ( @joshuaabenazer )
- [x] Lightbox  ( @yapapaya )
- [x] Plupload ( @yapapaya, @joshuaabenazer   )
- [x] Upload from activity update box (basic, like current buddypress-media)  ( @yapapaya )
- [x] Backbone.js ( @yapapaya, @joshuaabenazer )
- [x] Database upgrade script for new "Global Album"  (@faishal, @desaiuditd )
- [x] Premium Addon Update - FFMPEG (@joshuaabenazer)
- [x] Premium Addon Update - Kaltura (@joshuaabenazer)
- [x] Premium Addon Update - Tagging (@yapapaya)
- [x] Premium Addon Update - Instagram(@joshuaabenazer)
- [x] Backend Admin Settings (@desaiuditd)
- [x] Rename this repo! ;-)
